"""Initial migration.

Revision ID: 081f9088be36
Revises: 8a8725c0f131
Create Date: 2024-07-14 00:36:55.604632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081f9088be36'
down_revision = '8a8725c0f131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
