"""Initial migration.

Revision ID: 355bf47d2869
Revises: 081f9088be36
Create Date: 2024-07-15 16:03:47.416903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355bf47d2869'
down_revision = '081f9088be36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joke_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['joke_id'], ['joke.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
